server:
  port: 0

spring:
  application:
    name: orderService
  datasource:
    url: jdbc:h2:~/orderservice
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: saechim-interior
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
logging:
  level: debug