server:
  port: 0

spring:
  application:
    name: userService
  datasource:
    url: jdbc:h2:tcp://localhost/~/userservice
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

logging:
  level:
    saechim.userservice.userservice.service: debug

token:
  validity: 172800000
  secretKey: saechimdaekiIsInstanceofcomputerJunseongabcdefghijklmnopqrstuvwxyz


