server:
  port: 0

spring:
  application:
    name: homeService
  datasource:
    url: jdbc:h2:tcp://localhost/~/homeservice
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
