server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/userservice/(?<segment>.*), /$\{segment}

        - id: homeService
          uri: lb://HOMESERVICE
          predicates:
            - Path=/homeservice/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/homeservice/(?<segment>.*), /$\{segment}

        - id: categoryService
          uri: lb://CATEGORYSERVICE
          predicates:
            - Path=/categoryservice/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/categoryservice/(?<segment>.*), /$\{segment}

        - id: etcService
          uri: lb://ETCSERVICE
          predicates:
            - Path=/etcservice/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/etcservice/(?<segment>.*), /$\{segment}

        - id: storyService
          uri: lb://STORYSERVICE
          predicates:
            - Path=/storyservice/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/storyservice/(?<segment>.*), /$\{segment}

        - id: userService
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**
            - Method= POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/userservice/(?<segment>.*), /$\{segment}

        - id: userService
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**
            - Method= GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/userservice/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter




token:
  validity: 172800000
  secretKey: saechimdaekiIsInstanceofcomputerJunseongabcdefghijklmnopqrstuvwxyz


